runtime: nodejs
env: flex

# The following env variables may contain sensitive information that grants
# anyone access to your database. Do not add this file to your source control.
env_variables:
  DB_USER: "root"
  DB_PASS: "Mhz1KjwHvseamjt7"
  DB_NAME: "SongSearch"
  # e.g. my-awesome-project:us-central1:my-cloud-sql-instance
  INSTANCE_CONNECTION_NAME: "ssst-finalproj:us-central1:ssst-proj"

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: "ssst-finalproj:us-central1:ssst-proj"